#!/usr/bin/env python3
"""Run the invocations generated by generate_invocations.py.

Each invocation is executed in its own temporary directory,
into which the input files of the invocation are copied first, so that the tool only
reads and writes files in that directory. The combined output (stdout and stderr)
of the command is written to the log file of the invocation. The output files that
the command produced are moved from the temporary directory to their destination.
"""

import argparse
import json
import os
import re
import shlex
import shutil
import signal
import subprocess
import sys
import tempfile
import time
from pathlib import Path

# The root of the repository. The binary and the input files of an invocation are relative
# to it, whereas its log and its output files are relative to the current directory.
ROOT = Path(__file__).resolve().parent.parent

# A line of the tool output that indicates a failure even if the return code is 0.
ERROR_LINE = re.compile(r"^ERROR\b.*$", re.MULTILINE)

# Seconds to wait for a killed process to actually terminate.
KILL_GRACE = 5


def resolve_binary(bin):
    """The absolute path of the tool binary."""
    path = Path(os.path.expanduser(bin))
    if not path.is_absolute():
        if len(path.parts) == 1:
            found = shutil.which(str(path))
            if found:
                return Path(found)
        path = ROOT / path
    return path


def prepare(invocation):
    """The command line (with the absolute path of the binary) and the input files of an invocation.

    Raises ValueError if the binary or an input file does not exist.
    """
    binary = resolve_binary(invocation["command"][0])
    if not binary.is_file():
        raise ValueError(f"binary not found: {binary}")
    input_files = [ROOT / file for file in invocation["input-files"]]
    for file in input_files:
        if not file.is_file():
            raise ValueError(f"input file not found: {file}")
    return [str(binary), *invocation["command"][1:]], input_files


def execute(args, cwd, timelimit):
    """Run a command, aborting it when it exceeds the time limit.

    Returns (output, wall_time, return_code); the return code is None on a timeout.
    """
    start = time.time()
    # Own session, so that the whole process tree can be killed on a timeout.
    proc = subprocess.Popen(args, cwd=cwd, stdin=subprocess.DEVNULL,
                            stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
                            start_new_session=True)
    timeout = False
    try:
        try:
            output, _ = proc.communicate(timeout=timelimit)
        except subprocess.TimeoutExpired:
            timeout = True
            output = terminate(proc)
    except KeyboardInterrupt:
        terminate(proc)
        raise
    wall_time = time.time() - start
    return output.decode("utf8", errors="replace"), wall_time, None if timeout else proc.returncode


def terminate(proc):
    """Kill the process tree of proc and return whatever output it produced."""
    for sig in (signal.SIGTERM, signal.SIGKILL):
        try:
            os.killpg(proc.pid, sig)
        except ProcessLookupError:
            break
        try:
            output, _ = proc.communicate(timeout=KILL_GRACE)
            return output
        except subprocess.TimeoutExpired:
            continue
    try:
        output, _ = proc.communicate(timeout=KILL_GRACE)
    except subprocess.TimeoutExpired:
        output = b""
    return output


def collect_output(invocation, tmp):
    """Move the output files from the temporary directory to their destination.

    Returns the output files of the invocation that were produced and those that were not.
    """
    produced, missing = [], []
    for file in invocation["output-files"]:
        destination = Path(file)
        source = Path(tmp) / destination.name
        if source.is_file():
            destination.parent.mkdir(parents=True, exist_ok=True)
            shutil.move(source, destination)
            produced.append(file)
        else:
            # Do not keep the file of a previous run of this invocation.
            destination.unlink(missing_ok=True)
            missing.append(file)
    return produced, missing


def run(invocation, tmpdir):
    """Run a single invocation and write its log file. Returns a status string."""
    config, benchmark = invocation["config"], invocation["benchmark"]
    log = Path(invocation["log"])
    timelimit = invocation["timelimit"]

    log.parent.mkdir(parents=True, exist_ok=True)
    try:
        args, input_files = prepare(invocation)
    except ValueError as e:
        log.write_text(f"Error:\t{e}\n")
        return "error", 0.0, str(e)

    with tempfile.TemporaryDirectory(prefix="invocation-", dir=tmpdir) as tmp:
        for file in input_files:
            shutil.copy2(file, Path(tmp) / file.name)
        output, wall_time, return_code = execute(args, tmp, timelimit)
        produced, missing = collect_output(invocation, tmp)

    header = (f"Command:\t{shlex.join(args)}\n"
              f"Benchmark:\t{benchmark['id']}\n"
              f"Configuration:\t{config['id']}\n"
              f"Repetition:\t{invocation.get('repetition', 1)}\n"
              f"Time limit:\t{timelimit}\n"
              f"Output:\n")
    footer = f"\n{'-' * 40}\nWallclock time:\t{wall_time:.3f}\nReturn code:\t{return_code}\n"
    footer += "".join(f"Output file:\t{file}\n" for file in produced)
    footer += "".join(f"Missing output file:\t{file}\n" for file in missing)
    if return_code is None:
        footer += (f"Computation aborted after {wall_time:.3f} seconds since the time limit "
                   f"of {timelimit} seconds was exceeded.\n")
    log.write_text(header + output + footer)

    if return_code is None:
        return "timeout", wall_time, None
    if return_code != 0:
        return "error", wall_time, f"return code {return_code}"
    error = ERROR_LINE.search(output)
    if error:
        return "error", wall_time, f"tool reported: {error.group(0).strip()}"
    if missing:
        return "error", wall_time, f"output file not produced: {', '.join(missing)}"
    return "ok", wall_time, None


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("invocations", help="json file as written by generate_invocations.py")
    parser.add_argument("--entry", type=int, metavar="I",
                        help="run only the I-th invocation (1-based, as numbered in the output)")
    parser.add_argument("--tmpdir",
                        help="directory in which the temporary directories of the invocations "
                             "are created (default: the temporary directory of the system)")
    parser.add_argument("--dry-run", action="store_true",
                        help="only show what would be run, do not execute anything")
    args = parser.parse_args()

    with open(args.invocations) as f:
        invocations = json.load(f)
    if not isinstance(invocations, list):
        sys.exit(f"{args.invocations}: expected a JSON array")

    selected = list(enumerate(invocations, start=1))
    if args.entry is not None:
        if not 1 <= args.entry <= len(invocations):
            sys.exit(f"--entry must be between 1 and {len(invocations)}, got {args.entry}")
        selected = [selected[args.entry - 1]]

    if args.dry_run:
        for _, invocation in selected:
            try:
                command, _ = prepare(invocation)
            except ValueError as e:
                print(f"! {e}")
                continue
            print(f"{invocation['log']}: {shlex.join(command)}")
        return

    counts = {"ok": 0, "timeout": 0, "error": 0}
    width = len(str(len(invocations)))
    for number, invocation in selected:
        label = f"{invocation['config']['id']} {invocation['benchmark']['id']}"
        if "repetition" in invocation:
            label += f" rep{invocation['repetition']}"
        print(f"[{number:>{width}}/{len(invocations)}] {label} ... ", end="", flush=True)
        try:
            status, wall_time, note = run(invocation, args.tmpdir)
        except KeyboardInterrupt:
            print("interrupted")
            sys.exit("aborted")
        counts[status] += 1
        print(f"{status} ({wall_time:.1f}s)" + (f": {note}" if note else ""), flush=True)

    print(f"\n{len(selected)} invocations: "
          f"{counts['ok']} ok, {counts['timeout']} timeout, {counts['error']} error")


if __name__ == "__main__":
    main()
